### ISSUE TITLE
[Java*] Merge beanValidation/beanValidationParams.mustache

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#4719]
##### Description

From #4615: Implement decision of merging beanValidation/beanValidationParams.mustache at the cost of losing the newlines in beanValidation.mustache but with the plus of having to maintain only a single file for all the beanvalidation annotations.

Languages to be updated:
 - [x] jaxrs-cxf-cdi 
 - [x] jaxrs-spec - see PR #4731 
 - [x] jaxrs (Jersey) - see PR #4732
 - [x] jaxrs-cxf- see PR #4733
 - [x] jaxrs-resteasy - see PR #4734
 - [x] java - see PR #4735
 - [x] spring - see PR #4736

This issue covers also #4711, if beanValidationPathParams/QueryParams are also split during the update, otherwise this has to be done separately.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Related issues

PR #4615 - there the decision was concluded.

**Comment by jfiala** [comment]
Implemented merge for jaxrs-cxf-cdi, see PR #4723

**Comment by jfiala** [comment]
@nickcmaynard 

Overview of existing beanvalidation annotations from swagger-with-fake....yaml:

Parameters:
* @NotNull: PetApi.findPetsByStatus(@NotNull ..List<String> status)
* @Min/@Max: StoreApi.getOrderById(@Min(1) @Max(5) ..Long orderId)
* @DecimalMin / @DecimalMax: no sample yet
* @Pattern:  no sample yet
* @Size:  no sample yet

Model:
* @NotNull: Pet.getName(), Pet.getPhotoUrls (List<String>)
* @Min/@Max: FormatTest.getInt32() @Min(20)  @Max(200)
* @DecimalMin / @DecimalMax: FormatTest.getNumber @DecimalMin("32.1") @DecimalMax("543.2")
* @Pattern: FormatTest: getString() @Pattern(regexp="/[a-z]/i")
* @Size: FormatTest.getPassword() @Size(min=10,max=64)

Additionally we can cross out Min/Max and Size(min=/max).
So we could add some more variations to the FormatTest of the swagger-with-fake....yaml, is that what you mean?

Is there any sample of how to assert the generated Parameters/Model annotations with a Junit-test or do we need to set this up (pls see also #4721, I'd prefer to add a Java-based Generator Util class and then a test based on the sample results?
So I'd like first make sure that the samples are always up to date and then do assertions on the various snippets to make sure they stay the same over time.

**Comment by jfiala** [comment]
created separate PRs for all Java* languages

**Comment by nickcmaynard** [comment]
I'll confess I'm not sure I understand. My comment in #4723 was focused on expecting to see *some* changes in the samples given the removal of newlines.

Please could you explain further? Perhaps I'm lacking some context.

**Comment by jfiala** [comment]
most of the PRs only show few changes, but it seems some samples are not up to date, for jaxrs-spec there are wrong samples generated.
jaxrs-spec: 40 files due to wrong files generated by shellscript (using Jersey instead of jaxrs-spec templates)
Jersey: 5 files OK
cxf: 7 files OK
resteasy: 4 files OK
Java: 4 files OK
spring: 15 files, samples seem to be outdated, I generated using petstore-with-fake-endpoints-models-for-testing.yaml 

IMHO we should get rid of all the shellscripts and replace with a Java-based solution + Junit-tests, this would make it a lot easier to keep the samples *always* up to date & consistent.

**Comment by jfiala** [comment]
Of course we lost the beauty of beanval. annotations in the models, but that's how the solution is designed now. IMHO it would be way better to have 1 beanval file for *all* Java languages and reuse them in all the Java languages. This way we could also afford having 2 (one for params and one for models) with nicer formatting as it was.

**Comment by jfiala** [comment]
beanValidation/beanValidationParams.mustache have been merged completely.
